### ISSUE TITLE
[FEA] UMAP umap_learn integration metaissue

### ISSUE THREAD

**Issue by lmeyerov** [graphistry/pygraphistry#290]
**Is your feature request related to a problem? Please describe.**

Using umap_learn with graphistry should be more visible and easier!

See: https://github.com/graphistry/pygraphistry/blob/master/demos/demos_databases_apis/umap_learn/umap_learn.ipynb

**Describe the solution you'd like**

- [ ] umap_learn: `embedding.plot()` 
  - [ ] method + docs on their side <- maintainers already signaled interest
- [ ] pygraphistry: `g = g.nodes(...).umap(engine='umap_learn', params=...); print(g._embeddings); g.plot()`
- [ ] attributes: options not just for embedding, but original properties + potentially vectorized features
- [ ] maybe some recommended settings or enrichments, like:
  - compact layout
  - color edges by similarity

**Comment by lmeyerov** [comment]
@lmcinnes  FYI :)

**Comment by lmeyerov** [comment]
Moving discussion to https://github.com/graphistry/pygraphistry/discussions/300
